name: bondnet
channels:
  - pytorch
  - dglteam
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - boost=1.74.0
  - cudatoolkit=11.3.1
  - dgl=0.5.0
  - dgl-cuda11.3=0.9.1
  - intel-openmp=2021.4.0
  - ipykernel=5.5.5
  - ipython=7.33.0
  - matplotlib-base=3.5.3
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openbabel=3.1.1
  - pandas=1.3.5
  - pickleshare=0.7.5
  - pip=22.2.2
  - pycparser=2.21
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.7.12
  - pytorch=1.12.1=py3.7_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - rdkit=2022.03.4
  - setuptools=65.4.1
  - tqdm=4.64.1
  - pip:
      - ase==3.22.0
      - h5py==3.7.0
      - joblib==1.2.0
      - ipython==7.33.0
      - kaleido==0.2.1
      - lightning-utilities==0.7.1
      - lmdb==1.4.1
      - notebook==6.5.4
      - networkx==2.6.3
      - pathtools==0.1.2
      - pebble==5.0.1
      - plotly==5.10.0
      - protobuf==3.20.3
      - psutil==5.9.0
      - pydeprecate==0.3.2
      - pymatgen==2022.0.17
      - pymongo==4.3.3
      - pytest==7.3.2
      - pytorch-lightning==1.9.5
      - pytorch-lightning-bolts==0.3.2.post1
      - pyyaml==6.0
      - scikit-learn==1.0.2
      - scipy==1.5.4
      - shortuuid==1.0.9
      - spglib==2.0.1
      - sympy==1.10.1
      - tenacity==8.1.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboard==2.11.2
      - threadpoolctl==3.1.0
      - torchmetrics==0.11.1
      - wandb==0.15.3
