name: bondnet
channels:
  - conda-forge
  - pytorch
  - dglteam
  - defaults
dependencies:
  - pip
  - pymatgen==2020.6.8
  - rdkit==2020.03.3
  - openbabel==3.1.1
  - pytorch==1.5.0
  - torchvision
  - dgl==0.4.3
